services:
  database:
    image: postgres:18-alpine
    environment:
      TZ: 'GMT-4'
      PGTZ: 'GMT-4'
    env_file:
      - ".env.prod"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "psc" ]
      start_period: 5s
    volumes:
      - "./pgdata:/var/lib/postgresql"
  minio:
    image: quay.io/minio/minio:latest
    command: [ "server", "--console-address", ":9001", "/data" ]
    volumes:
      - "./minio:/data"
    env_file:
      - ".env.prod"
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ".env.prod"
    depends_on:
      database:
        condition: service_healthy
        restart: true
