services:
  database:
    image: postgres:18-alpine
    environment:
      TZ: 'GMT-4'
      PGTZ: 'GMT-4'
    env_file:
      - ".env.prod"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "blog" ]
      start_period: 5s
    volumes:
      - "./pgdata:/var/lib/postgresql"
  minio:
    image: quay.io/minio/minio:latest
    command: [ "server", "--console-address", ":9001", "/data" ]
    volumes:
      - "./minio:/data"
    env_file:
      - ".env.prod"
  minio-buckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    restart: on-failure
    env_file:
      - ".env.prod"
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set dockerminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb dockerminio/covers;
      exit 0;
      "
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ".env.prod"
    depends_on:
      - database
