services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: psc
      POSTGRES_USER: postgres
      TZ: 'GMT-4'
      PGTZ: 'GMT-4'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "blog" ]
      start_period: 5s
    ports:
      - "5432:5432"